{% set name = "canmatrix" %}
{% set version = "0.9.5" %}
{% set sha256 = "3fbfffe4e0ca348722bacdc46dbd1e7a64205842a937dfc05ef31815abae292d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3fbfffe4e0ca348722bacdc46dbd1e7a64205842a937dfc05ef31815abae292d

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - xlwt
    - xlrd
    - xlsxwriter
    - pyyaml
    - lxml
    - future
    - attrs >=19.2.0
    - click
    - six

test:
  imports:
    - canmatrix
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ebroecker/canmatrix
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Converting Can (Controller Area Network) Database Formats .arxml .dbc .dbf .kcd ... '
  description: |
    Canmatrix implements a "Python Can Matrix Object" which describes the can-communication and the needed objects (Boardunits, Frames, Signals, Values, ...) 
    Canmatrix also includes two Tools (canconvert and cancompare) for converting and comparing CAN databases.
    
    There are several importers (read) and exporters (write) for this object.
    
    supported file formats for import:
    
        .dbc candb / Vector
        .dbf Busmaster (open source!)
        .kcd kayak (open source!)
        .arxml autosar system description
        .yaml dump of the python object
        .xls(x) excel xls-import, works with .xls-file generated by this lib
        .sym peak pcan can description
    
    supported file formats for export:
    
        .dbc
        .dbf
        .kcd
        .xls(x)
        .json Canard (open source!)
        .arxml (very basic implementation)
        .yaml (dump of the python object)
        .sym
        .xml fibex

  doc_url: https://canmatrix.readthedocs.io/en/latest/
  dev_url: https://github.com/ebroecker/canmatrix

extra:
  recipe-maintainers:
    - ebroecker
    - altendky
    - danielhrisca
