{% set name = "canmatrix" %}
{% set version = "0.8" %}
{% set sha256 = "9837ab53a407037ba8d5dbba235cecc69c4a7ff02f5221db721088815493f1d7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  
  fn: canmatrix-0.8.tar.gz
  url: https://files.pythonhosted.org/packages/50/b4/d2fadf4fa14e56e0fa3c95de8ce87b980e72530bb043f4d9f26d764f97c4/canmatrix-0.8.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python
  entry_points:
    - cancompare = canmatrix.compare:main
    - canconvert = canmatrix.convert:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - xlwt
    - xlrd
    - xlsxwriter
    - pyyaml
    - lxml
    - future
    - attrs>=18.1.0

test:
  imports:
    - canmatrix
    
  commands:
    - cancompare -h
    - canconvert -h

about:
  home: https://github.com/ebroecker/canmatrix
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Converting Can (Controller Area Network) Database Formats .arxml .dbc .dbf .kcd ... '
  description: |
    Canmatrix implements a "Python Can Matrix Object" which describes the can-communication and the needed objects (Boardunits, Frames, Signals, Values, ...) 
    Canmatrix also includes two Tools (canconvert and cancompare) for converting and comparing CAN databases.
    
    There are several importers (read) and exporters (write) for this object.
    
    supported file formats for import:
    
        .dbc candb / Vector
        .dbf Busmaster (open source!)
        .kcd kayak (open source!)
        .arxml autosar system description
        .yaml dump of the python object
        .xls(x) excel xls-import, works with .xls-file generated by this lib
        .sym peak pcan can description
    
    supported file formats for export:
    
        .dbc
        .dbf
        .kcd
        .xls(x)
        .json Canard (open source!)
        .arxml (very basic implementation)
        .yaml (dump of the python object)
        .sym
        .xml fibex

  doc_url: 
  dev_url: https://github.com/ebroecker/canmatrix

extra:
  recipe-maintainers:
    - ebroecker
    - altendky
    - danielhrisca
