travis:
  secure:
    BINSTAR_TOKEN: yELq+TNGjfPE1vv6pRHc71N7mMMu0qCkAZtyEusapMOSy/P4NcXh3e0R8RTva3Qdq5Yd0PP73AbwomwlvgyWPkd4yjDeFX5sh7ysBYIqPu9ruNaEruqnteo0vs+YuY8L5/R9/W9h7X+xRS53PGVY6G8MCR4zytJlCwa/mA9yV4HbFjrzh0vAHfq8FHnfTjs13TXm1lKwFKtiwc7HlEn5Z7rHKZT0ul5faMRiqjlmGjh3s+bw6+oNOfgphKXzVjwJk61e8dKIgIqTy9rFqYaZTb2HN2o7dgttJ+MdNQKU0uTqrH361uEJYtivVGvyKjqGXOyLwNkE0ZVoDxJ4gmcaLyJu7TlkqCzQs/ODJwqEuvwpXng27AGAsYmdUWwgKQecckvWqksWNUjwcuSEcvQBxhWiMYIhI2pGBPzEUuu+T+S6lkyxriaWIjBQuHFCMdrSQa6P8t31artqc6Q6P0NuaCiEansP/49VsjF/GJoECzVVlqqIorHcT+jgtp4rBDMigv9bQdMVPtPaXl71kLc+lgE5xkZUV1G4plm0YNkSTWtwf7CFf2mO7KSDICCrNd37J1HOPq50CjXBF2xdV+1AVLynJaEwg6jQmTU5s9/D/QLXsCcJiJoSnDo+MgyGrKkB2Alf/NFrJlj/OtFcxH8itkp+KjlHnqGiVm5D/zPxlyE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
