travis:
  secure:
    BINSTAR_TOKEN: Zx1LdPw6TqQId5EwB466wxMwy3JAw0xpZPFT6do1lyBwB99qMNdvZtx6YCjPGRZMRBKH+PcAqU1WH37FcBFz9zPawryAujD9IL6yb2Wwnsf0H3qH8pi1oid5Wo/04bVXZnDd7a4wSt+AiCiZ2YCt0QK8gkvPS0BRCTnfBh0lSf8oSt0Ky4qkCZXDoWWXlyKGgLqVKDfN1Sp0i02SgIFlRMFhFG3B18tW7HAHboNUq+Kn21oKoXdfl1gbuFHRgIgixUz/XIMLsTf/GWgBAmvkRYWeGsyOnqJnnAQ/tcYFhZTIBsVL10d6SW8YSCS9FODg+pAjmMJjc6mVhzDHS0kC2vRd1HPly76WAlh83m/NsVVmmZBNljcXVHrfuXtvaydA5j4A8FLG31x00nsF7dSZ6szLmoc9GEAYRbrvIj/x30qYaybk4i51lDUyyNp5i9Pc+VQmfzi9L9nE37HwGlX//q1ZMdGRekRyfLlAE+cIoZ/gpIBNc2R3/wsOvVpnq8ChlXvlyRwCeFDct44QTUIiMAoYJMNmWdY/R4ouIE6fTrEFtQSMroJnaeQqWuYoqQxKTTeB3zXYrNYHFIWpGyIjBTyTHlYQdyUvYAr1DlO2nHwikGbqCJDdeRWGrHaYZnTxmEkduIY5oz5e0VntX/VDcY2nQrUFOEEmAMY3uQY19GE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
