travis:
  secure:
    BINSTAR_TOKEN: PLvjmrWttQEgNQEs0xxCex41uO77F8vfSW9YSxsETxxPj3WGPEU5LluoXn2Gu7Kaje+ejipOdMsSZ2rx9PEdscZnTtzI9iOQes7Ac/fgW8DTC9NT15id89f20BRiUX7B1a/Cnbuar1pejbr9YQGMAF4/jLpeSRYs5k4/vGIuZ1MC+b1Q04bYGlGaw4tsPIjQU6bHEA4yhmmLIyreDfoA701gg66pz4WaSh354caFzrfdcjBAOEgDBgJoEbOz7m3V0XHRtRk7SAGd28ehbYTjDeUu+l/mlY6QOt2bS3zB3PMUxvI8pCz9ZgM963cbGi8XUFZOggDxXTGQyT2dSEf7ywPQ5zUTr70Oy7H6j0Lxig42Je0ZKVOxLUg5BX3O6tu4FTOvagKJZXMCg9XxkWMFLRF1NDP7kq9+6oX5ZRn4k94VWsX+fGymUILo4ikQRlmJTyDW460zIDlRlTCLLwFmyeG9EQC8SxYg3Ybf4OxpuXWkO0y6PtYA6PyNXyCbLWrhTUPB94AHCAiIOxWY9RHSWc0bNGTak1G+t948FdnOscmC9mBvPzIXCZcmZmu8d0F5eXrm/rdT5tLCG9LQ32jGx538IOwSQtNXzcm1O1A5FAsC6zq0fGuZ86u4iQ23BX7HY55KDRs24Rl0txt198XQFnBqseFh7K0CNjSQE014NmU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
